🐛(hooks) make post-deploy scripts more reliable
Hook scripts should fail when a command fails. And we should prevent
unexpected substitutions.

diff --git a/src/hooks/post-deploy b/src/hooks/post-deploy
--- a/src/hooks/post-deploy
+++ b/src/hooks/post-deploy
@@ -1,5 +1,7 @@
 #!/bin/env sh
 
+set -e
+
 GRAFANA_AUTH="${GRAFANA_API_USER}:${GRAFANA_API_PASSWORD}"
 GRAFANA_ROOT_URL="${GRAFANA_ROOT_URL:-http://grafana:3000}"
 REQUEST_CONTENT_TYPE="Content-Type: application/json"
@@ -12,6 +14,11 @@ teachers_folder_uid=$(
     "${GRAFANA_ROOT_URL}/api/search?query=Course%20video%20details&type=dash-db" | \
   jq -r .[0].uid
 )
+
+if [[ -z teachers_folder_uid ]]; then
+  echo "Teachers folder not found!"
+  exit 1
+fi
 
 # Substitute
 sed -i "s/%%teachers_folder_uid%%/${teachers_folder_uid}/g" "${COURSE_DASHBOARD_PATH}"
